site_name: NioChat
site_description: Sistema completo de atendimento via WhatsApp com IA
site_author: Junior Silva
site_url: https://niochat.com.br

repo_name: juniorssilvaa/niochat
repo_url: https://github.com/juniorssilvaa/niochat
edit_uri: edit/main/docs/

docs_dir: docs_content

theme:
  name: material
  language: pt-BR
  logo: assets/mkdocs.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Modo claro

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/juniorssilvaa/niochat
    - icon: fontawesome/brands/whatsapp
      link: https://app.niochat.com.br
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/juniorssilvaa
  generator: false

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - admonition
  - def_list
  - attr_list
  - codehilite
  - footnotes
  - abbr
  - md_in_html

plugins:
  - search
  - minify
  - git-revision-date-localized:
      locale: pt_BR

nav:
  - Início: index.md
  - Visão Geral:
    - Introdução: overview/introduction.md
    - Arquitetura: overview/architecture.md
    - Funcionalidades: overview/features.md
  - Instalação:
    - Desenvolvimento: installation/development.md
    - Produção: installation/production.md
  - Configuração:
    - Supabase: configuration/supabase.md
  - Uso:
    - Interface: usage/interface.md
  - API:
    - Autenticação: api/authentication.md
    - Endpoints: api/endpoints.md
    - Guia do Postman: api/postman-guide.md
    - WebSocket: api/websocket.md
    - Webhooks: api/webhooks.md
  - IA e SGP:
    - Configuração IA: ai/configuration.md
  - Supabase:
    - Integração: supabase/integration.md
  - Desenvolvimento:
    - Troubleshooting: development/troubleshooting.md
  - Changelog: changelog.md
