# Generated by Django 5.2.4 on 2025-07-14 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_canalwhatsapp_options_canalemail_canalfacebook_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='canalfacebook',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='canalfacebook',
            name='provedor',
        ),
        migrations.AlterUniqueTogether(
            name='canalinstagram',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='canalinstagram',
            name='provedor',
        ),
        migrations.AlterUniqueTogether(
            name='canaltelegram',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='canaltelegram',
            name='provedor',
        ),
        migrations.AlterUniqueTogether(
            name='canalwebsite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='canalwebsite',
            name='provedor',
        ),
        migrations.AlterUniqueTogether(
            name='canalwhatsapp',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='canalwhatsapp',
            name='provedor',
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email'), ('website', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('page_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais', to='core.provedor')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
                'unique_together': {('provedor', 'tipo', 'username', 'email', 'url', 'page_id', 'chat_id')},
            },
        ),
        migrations.DeleteModel(
            name='CanalEmail',
        ),
        migrations.DeleteModel(
            name='CanalFacebook',
        ),
        migrations.DeleteModel(
            name='CanalInstagram',
        ),
        migrations.DeleteModel(
            name='CanalTelegram',
        ),
        migrations.DeleteModel(
            name='CanalWebsite',
        ),
        migrations.DeleteModel(
            name='CanalWhatsapp',
        ),
    ]
